### ISSUE TITLE
Wierd artefacs

### ISSUE THREAD

**Issue by fkreiner** [migueldemoura/myazo#13]
I get wierd artefacts when taking a screenshot. The selection rectangle flickers around in wierd shapes.
Sometimes it shows in the screenshot. Like this: https://kreiner.me/i/e019c2f8c66d0e5699df4b95.png

Python 3.5.2
KDE Neon with KDE Plasma 5.12.5
Ubuntu 16.04

**Comment by migueldemoura** [comment]
I'm guessing that's due to ImageMagick's `import`. You can try running `import` from the terminal directly and see if you get the flickers.

According to https://packages.ubuntu.com/bionic/kubuntu-desktop, the default screenshot tool in Kubuntu 18.04 is `kde-spectacle`, replacing `ksnapshot` (the one you probably have installed). I'll add a preset for both.

**Comment by migueldemoura** [comment]
Can you try running it directly? You can also double-click to finish.

```shell
spectacle -b -n -r
```

**Comment by fkreiner** [comment]
It seems it was a problem with my terminal trying to grab the keys.
It works flawlessly now! Thank you very much!

**Comment by migueldemoura** [comment]
Awesome, glad I could help!
